name: "Zig Installer"

on:
# debug:
#  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        description: 'Runner OS'
        required: true
        type: string
      use-cache:
        description: 'Zig Cache'
        required: true
        default: true
        type: boolean
      ext-cache:
        description: 'Cache Extension'
        required: false
        default: 'AAA'
        type: string
      zig-version:
        description: 'Zig Version'
        required: true
        type: string
        default: 0.9.1

jobs:
  zig-install:
    name: ZIG Install on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
    env:
      ZIG_VERSION: ${{ inputs.zig-version }}
    steps:
      - name: Pull zig-helper
        uses: actions/checkout@v3
        with:
          repository: rinse-repeat/zig-gh-helper
          path: zig-helper
      - name: Setup ZIG Environment Vars
        shell: bash
        run: |
          source ./zig-helper/zig_map.sh
          setup_runner_nix $GITHUB_ENV ${{ inputs.os }}
          export | grep ZIG
      - name: Setup ZIG Checksum
        shell: bash
        run: |
          export ZIG_CHECKSUM=`cat ./zig-helper/zig-checksums-${{ inputs.zig-version }}.json | jq --raw-output ".[\"${{ env.ZIG_RUNNER_OS }}_${{ env.ZIG_RUNNER_ARCH }}\"]"`
          echo "ZIG_CHECKSUM=$ZIG_CHECKSUM" | tee -a $GITHUB_ENV
      - name: Cache ZIG
        if: ${{ inputs.use-cache == true }}
        uses: actions/cache@v3
        with:
          key: zig-${{ inputs.os }}-${{ inputs.zig-version }}-${{ inputs.ext-cache }}
          path: ~/zig          
      - name: Setup ZIG
        shell: bash
        run: |
          source ./zig-helper/zig_map.sh
          #cat $GITHUV_ENV
          zig_install_nix ${{ inputs.os }}
          find $HOME -type f -name \*zig\*
          find $HOME -type d -name \*zig\*
